name: 'Deploy'

on: workflow_dispatch

jobs:
  deploy-api:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@main

      - name: Deploy API
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: cph-scorer-api
          heroku_email: corentin.verquin@gmail.com